### ISSUE TITLE
Editorial: Section 4 last sentence 2 paragraph

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-connect-udp#127]
Section 4 last sentence 2 paragraph is: 

`Once allocated, any context ID can be used by both client and proxy - only allocation carries separate namespaces to avoid requiring synchronization.`

Why is there a "-"? Actually not sure what the second is supposed to say. Is there anything missing?

**Comment by DavidSchinazi** [comment]
The dash has meaning similar to parentheses: it is equivalent to `Once allocated, any context ID can be used by both client and proxy (only allocation carries separate namespaces to avoid requiring synchronization).` (see [Grammarly definition](https://www.grammarly.com/blog/dash/)).

This parenthetical clause adds context to the main clause: allocation is separate but usage is not.

**Comment by DavidSchinazi** [comment]
Do you have a suggestion for text that would be better?

**Comment by LPardue** [comment]
I find the use of namespace in the quotedctext unhelpful. You might editorialize this sentence a bit anyway to improve the clarity. Something like

"Context ID allocation depends on restrictions to the use of even- and odd-numbered context IDs in order to avoid the need for synchronisation. However, once a context has been allocated, those restrictions no longer apply and context IDs can be used by any client or proxy, independent of who initially allocated them.

**Comment by mirjak** [comment]
Lucas thanks that's much better! (I think this "allocation carries" wording confused me a bit)
