### ISSUE TITLE
Security considerations

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-connect-udp#134]
Should we maybe add a recommendation to the sec considerations that proxies may limited the amount of data they send as long as they don't see any reply.

I guess initially you would limit to 10 packets and then following RFC8085 limit to one datagram per 3 seconds...?

Not sure if that really is a good idea but I wanted to bring it up for discussion...

**Comment by DavidSchinazi** [comment]
I thought about that when I first wrote the existing text, and I came to the conclusion that a limit here wouldn't protect against real attacks. If someone is attacking a closed UDP port, they're not accomplishing anything. If someone attacks an open UDP port (for example 443 because they want to attack someone's QUIC endpoint), then the target will reply with some sort of UDP packet (for example a QUIC RETRY) so this protection will disable itself. Does that make sense?

**Comment by LPardue** [comment]
The challenge I see with any advice is that the proxy is not an application using UDP, it's just passing opaque data. So it will really struggle to rationalise at all about the various UDP use cases that clients have for the proxy. 

Perhaps rather than focus on advice, focus on how CONNECT UDP proxy considerations differ from CONNECT TCP proxies. That may well cover, at the same time, considerations like how long should a proxy hold open requests (tunnels) that don't exchange any packets in one or both directions.

**Comment by DavidSchinazi** [comment]
That's discussed in the Proxy Handling section, it references BEHAVE for how long sockets should be kept open

**Comment by chris-wood** [comment]
@DavidSchinazi would it be worth adding your reasoning (which makes sense to me) to the draft somewhere?

**Comment by LPardue** [comment]
> That's discussed in the Proxy Handling section, it references BEHAVE for how long sockets should be kept open

fair point, I'd read that and forgotten about it, maybe worth a back reference from the security considerations. For instance, HTTP/2 has some special callouts to CONNECT in its security considerations https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#name-connect-issues

**Comment by DavidSchinazi** [comment]
That makes sense, I've written up #135 to address these comments.
