### ISSUE TITLE
UDP over what is required to supported? 

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-udp#141]
Section 3: 
'If the request is successful, the proxy commits to converting received HTTP Datagrams into UDP packets and vice versa until the tunnel is closed.'

I think it should say IP/UDP where IP is either IPv4 or IPv6 depending on what is supported on the proxy. I think the "target_host" implies IP level address of that target_host? However, it is not clear if any alternative lower layer to UDP is required to be supported.

**Comment by LPardue** [comment]
HTTP's definition of `CONNECT` doesn't include mention of IP, why should this deviate?

**Comment by gloinul** [comment]
Because there are no such thing as an UDP packet, there are IP packets with UDP. The targeting is requiring an IP address. So I think one really should acknowledge the assumption of IP.

**Comment by gloinul** [comment]
I disagree here. Connect-udp requires a target address, that is either a IPv4 or IPv6 literal or a DNS name for the proxy to resolve. With those limitations I think it can be made clear that that the connect-udp service is in fact to take an UDP payload and transform it into a IP/UDP packet with the given payload and IP and UDP header field set appropriately for the Connect request and any future extensions. Thus not being explicit and clear about the IP part is just trying to hid the fact that one need to care about the IP aspects of this transformation to.

**Comment by DavidSchinazi** [comment]
Hi Magnus, I understand that you're reading this through a transport lens, but this is fundamentally an HTTP layer document. In particular I'd invite you to read the following subsections of our references:
[RFC9110 s9.3.6](https://www.rfc-editor.org/rfc/authors/rfc9110.html#section-9.3.6) defines the CONNECT method in terms of request target and host
[RFC9110 s7.1](https://www.rfc-editor.org/rfc/authors/rfc9110.html#section-7.1) defines the request target in terms of a host
[RFC9110 s7.2](https://www.rfc-editor.org/rfc/authors/rfc9110.html#section-7.2) defines what a host is in terms of a URI host
[RFC3986 s3.2.2](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2) defines a URI host in terms of DNS and IP - in particular, that specification makes it clear that it can work with any version of IP

If the CONNECT-UDP document were to go into the details of IP, it would be overstepping its bounds and taking over what is fundamentally the purview of HTTP. In particular, we absolutely need to be agnostic about request targets so that updates to either the definition of a request target or a URI host would benefit this document. One of the core strengths of HTTP is its well defined API layer that allow changes to underpinnings without having to update higher layers.

When it comes to CONNECT-UDP extensions that wish to interact with the IP layers, there is absolutely no restriction there. As an example, the [ECN extension](https://www.ietf.org/archive/id/draft-schinazi-masque-connect-udp-ecn-02.html) can work just fine with the current version of the CONNECT-UDP document.

**Comment by gloinul** [comment]
It is not HTTP on the far side of the server. That is the side I am talking. Because the target and how the UDP payload is forward is no longer an HTTP aspect, it is "tunnel" encapsulation question. And I think the MASQUE Connect-UDP client has expectations on the server in regards to this. And there are IP level requirements in this document, for example on DF bit, something that I would note is very much IP version dependent on how one handle.

**Comment by DavidSchinazi** [comment]
Maybe I'm not quite understanding what you're asking for. What change to the document are you proposing?
