### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by mnot** [ietf-wg-masque/draft-ietf-masque-connect-udp#153]
> Responses to UDP proxying requests are not cacheable.

Try as we might, we can't retroactively place this requirement on the countless deployed caches on the Internet. Given that at least over HTTP/1.1 this mechanism uses GET, it might be better to specify that the GET response needs the appropriate caching metadata.

**Comment by DavidSchinazi** [comment]
Good catch. That particular text came from back when we only used CONNECT, as that's defined as non-cacheable. Since defining how to cache Upgrade sounds like dragons holding footguns, I'm just going to remove this text via #164. That way we rely on existing HTTP documents to properly define how caching works.
