### ISSUE TITLE
Additional options for CONNECT_UDP

### ISSUE THREAD

**Issue by martinduke** [ietf-wg-masque/draft-ietf-masque-connect-udp#19]
There are several things in the IP layer that a normal application running over a UDP socket can control: ECN, DSCP, etc. Magnus's draft is a comprehensive list, but these are the two with the strongest case (ECN being particularly compelling, IMO).

As an individual, I would be sad if there was no way to use ECN for MASQUE except to do IP proxying. As an AD, I think this functionality would absolutely be in scope if we could form a consensus around it.

I don't have a problem with support for this being optional, or even in a separate CONNECT-UDP extension draft, but I'm putting in issue here to preserve the discussion item. If the outcome is that someone needs to write an extension draft, I'm fine with that.

**Comment by DavidSchinazi** [comment]
I agree that there should be a mechanism that allows using ECN with CONNECT-UDP.

However, I feel strongly that this shouldn't be a required part of CONNECT-UDP, because
1. it's not required for a minimum viable product
2. some operating systems don't let user-space applications access this data from received UDP packets

Having it be an optional part of the CONNECT-UDP spec could be doable, but I'd personally prefer it to be its own draft and extension to CONNECT-UDP. That will prevent this topic from delaying the main CONNECT-UDP document.

**Comment by mirjak** [comment]
I think this is an important use that requires at minimum need to have some basic signalling mechanism build into the base protocol with a well defined extension point. However, if we do that, I think we can also specific the ECN signalling knowing that we want it. I would like to discuss how this could look like.

**Comment by LPardue** [comment]
What are the requirements of extensions such as this? 

I would hope that we can simply leverage the HTTP extension tools at our disposal rather than require anything additional. However, some of that hope depends on if extensions apply to a MASQUE tunnel connection, or individual CONNECT-UDP requests.

I'm more on the side of doing any work in a separate document to CONNECT-UDP.

**Comment by martinduke** [comment]
One of the harder issues is that we probably need per-DATAGRAM of what ECN bits came in on the packet. The most straightforward way to do this is to have optional fields in the H3 DATAGRAM frame, though I can understand why people might not like that.

**Comment by LPardue** [comment]
Oh, thanks for the clarification.

**Comment by ekr** [comment]
FWIW, I agree with @DavidSchinazi about this not going into the main draft.

**Comment by mirjak** [comment]
Even if this will be defined as an extension, we need to make sure we have the right extension point ready, e.g. for per-packet feedback. Also I think this is one of the base functions we should really support. I think we need more discussion based on a concrete proposal. Will try to work on this.

**Comment by DavidSchinazi** [comment]
The discussion around this issue points towards not adding ECN to the base spec, but ensuring that the base spec is extensible enough to allow building this as an extension. The design team refactor has ensured that we have the right extension point to enable this, so I'm closing this issue as out of scope for the base CONNECT-UDP spec. Please comment/reopen if you disagree and we can discuss at IETF 113.
