### ISSUE TITLE
ICMP handling on the proxy

### ISSUE THREAD

**Issue by obonaventure** [ietf-wg-masque/draft-ietf-masque-connect-udp#20]
With the CONNECT UDP, a proxy will send and receive UDP datagrams on behalf of a client. However, in addition to these UDP datagrams, it could also receive ICMP messages. The current draft does not discuss how these ICMP messages should be handled by a proxy and how they would need to be conveyed to the client. It probably makes sense to at least discuss how ICMP destination/network/port unreachable should be handled by the proxy (ignore, terminate the HTTP connection, ...)

**Comment by DavidSchinazi** [comment]
I agree. I'm not yet sure what the best solution is (closing the stream on port unreachable would improve reliability but does introduce a way for an attacker to deny service) but we should figure that out and provide guidance in the doc.

**Comment by ekr** [comment]
FWIW, the way TURN handles this is by having a way for the server to forward ICMP indications. 
https://www.rfc-editor.org/rfc/rfc8656.html#name-receiving-an-icmp-packet

Obviously, in order to have this in MASQUE we would need to have some sort of type indicator in the datagram.

**Comment by gloinul** [comment]
I do want the relevant information in the ICMP to make it to the client. However, ICMP falls into the asynchronous information that is not directly associated with a forwarded packet. It can clearly be a forwarded packet per EKR's suggestion. We have other cases where we have information that is related to the associated packet, for example ECN. So I think this there is an important high level design choice here that we need to sorted out. I think for the general extensibility lets consider a content identifier so that just UDP payloads can be separated from additional types with additional fields.
