### ISSUE TITLE
Next hop MASQUE proxy identity

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-udp#32]
So I think there are two different cases how chaining of MASQUE proxies may occurr.

Hop-by-hop: To my understanding is that this can occur when one masque proxy makes a decision based on either explicit signalling (would be extension) or an internal policy to forward the MASQUE proxying request to the next MASQUE server. So this can be done hiddenly from the client by the first one as part of an internal infrastructure from the MASQUE server provider, or it could be done towards an external one. For the later I think there exist the question if there should be any control over this. In RTSP 2.0 there exists a mechanism in Section  19.3 of RFC 7826 (https://www.rfc-editor.org/rfc/rfc7826.html#section-19.3) that enables the client to determine the identity of the next hop proxy. I don't know if this is needed for this, but I wanted to bring it up.

Onion routing: Where the client will use the first proxy to establish a UDP flow to the next masque proxy and then establish a HTTP/3 connection to that one to identify it explictly and then request one additional proxy flow. 

My main point to bring up this is the question if the models and how they work under HTTP provides the sequerity one would expect or if we simply need to note that the masque client is trusting that first proxy to establish that proxied flow and that is it. If it wants more control over any multi-hop then it needs to take the overhead of onion routing?

**Comment by DavidSchinazi** [comment]
Do you have a use-case where a client would want this level of control but where onion routing isn't the right solution?

**Comment by sysrqb** [comment]
> Do you have a use-case where a client would want this level of control but where onion routing isn't the right solution?

Nested QUIC connections impose the addition TLS handshake overhead, and wasted space due to nested headers. A variant of QUIC-Aware Proxying (https://datatracker.ietf.org/doc/html/draft-pauly-masque-quic-proxy-00) seems like a good starting point for reducing the header overhead.

`Accept-Credentials` is a good foundation for validating that the connection was correctly extended to a specific proxy, but its lacking a means of establishing shared cryptographic keys between the client and the (new) end proxy. A MASQUE extension should account for this.

I realize traffic analysis is considered outside the scope of MASQUE, but I'll quickly venture down that path anyway in case it's helpful. As I understand it, onion routing, as created by nested QUIC/TLS sessions, results in distinct connections IDs for every client. In multi-proxy onion routing this means that a network observer somewhere along the path can create precise profiles of that client's behavior and traffic patterns over time, even if they may not know the IP address of the client. This leakage may negate some of the benefits of using multiple proxies, depending on how the proxies are selected. With hop-by-hop, a proxy can coalesce client connections onto a single connection, and that multiplexing reduces this leakage.

**Comment by DavidSchinazi** [comment]
While there's interesting work to be done here, it is specific to QUIC-inside-QUIC and not applicable to generic CONNECT-UDP. I would suggest either bringing this to [draft-pauly-masque-quic-proxy](https://datatracker.ietf.org/doc/html/draft-pauly-masque-quic-proxy) or another extension. So I'm closing this issue with no action. Please reopen/comment if you disagree.
