### ISSUE TITLE
Datagram-Flow-Id header or just use a Chunk type?

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-masque/draft-ietf-masque-connect-udp#37]
The draft currently recommends use of a header to allocate datagram flow ids.  But it could equally use chunks to add these.  That might be a way to avoid over-allocation in the case that you need multiple flows.  Rather than allocating all the flows up front, they could be added as necessary.

**Comment by martinthomson** [comment]
@LPardue noted in the call today that intermediaries might want access to this information, so maybe frames (at the HTTP/2 or HTTP/3 layer) are better than chunks or headers.

**Comment by tfpauly** [comment]
@martinthomson What's an example of over-allocation in the current header scheme?

Given that the method should work across any HTTP version, I think making the flow ID header work the same across datagrams and stream chunks (as proposed in #38) would allow intermediaries to correctly translate, if necessary.

**Comment by martinthomson** [comment]
Let's say that you want to use flow identifiers to encode ECN markings.  Do you allocate all 4 flow identifiers to represent all possible options?  What if you never intend to use ECT1?  Are you allocating ECT1 on the off-chance that a packet arrives with that marking?

Basically, with the proposed ECN compression scheme, this results in a fixed commitment for every session.  However, if it were possible to signal additional mappings after establishing a flow, then you could add them just in time.  That has some race condition issues, but that could be resolved with buffering of various sorts and so it still might be preferable to having to know at the time you set things up what flows you need.

Think about the potential use of flows to map to connection IDs for relaying QUIC.

**Comment by tfpauly** [comment]
I think the argument that we're wasting flow IDs if we're reserving the numbers up front isn't particularly compelling given how large the space of IDs is, and that there isn't any need to actually allocate memory or state tracking for the ID values.

However, I do appreciate that being able to have flexible bindings allows us to do more dynamic things, particularly since for things like QUIC connection IDs, they can come and go more frequently.

How would the use of frames work?

**Comment by martinthomson** [comment]
We define a new frame type that carries the same information the header field does.  Use that frame to map flows to the request stream and attach any semantics you like to them.  It would likely require a setting to work properly.

**Comment by LPardue** [comment]
This sounds a bit like how PRIORITY_UPDATE is intended to work, it carries the same encoded values as the Priority header. We chose to restrict that to the control stream (or stream 0) because conventional requests close the stream in the send direction. CONNECT-* streams are by definition different because the stream remains open. I

**Comment by DavidSchinazi** [comment]
Overcome by events: Datagram-Flow-Id was removed in 649890881aaa92548b5a0fb37a7622b409b281fd. Closing.
