### ISSUE TITLE
What is the justification for dynamic context registration in CONNECT UDP?

### ISSUE THREAD

**Issue by afrind** [ietf-wg-masque/draft-ietf-masque-connect-udp#71]
Based on the current direction of the design team, I don't understand the justification for using dynamic context registration as the primary extension mechanism for CONNECT-UDP.  It seems like a more static format would be simpler and more performant, and cover the use-cases I'm aware of.  Specifically, use the bits of the varint at the beginning of a CONNECT-UDP datagram to determine the ECN state and/or presence of timestamps.

With this scheme, clients do not need to send any capsules, and servers do not need to buffer datagrams with an ID referencing an unregistered context.

If there is an extension that is more complicated and requires dynamic contexts, it can use a bit in the varint to indicate the presence of a context-ID.

**Comment by bemasc** [comment]
There is no way to signal whether endpoints actually support any "preregistered contexts", so (1) they must be decided Once And For All at specification time and (2) they all must be Mandatory To Implement.  That adds complexity to the minimal compliant implementation.

In contrast, dynamic registration adds no complexity burden to a simple implementation that doesn't support extensions.  It just has to (somehow...) say "NO" to any context registration attempt.

**Comment by DavidSchinazi** [comment]
> It seems like a more static format would be simpler and more performant

Can you elaborate on this? Sending a 3-byte capsule right after the headers is negligible overhead.

> Specifically, use the bits of the varint at the beginning of a CONNECT-UDP datagram to determine the ECN state and/or presence of timestamps.

This can be accomplished via dynamic allocations: just register 4 context IDs, one for each ECN value.

> If there is an extension that is more complicated and requires dynamic contexts, it can use a bit in the varint to indicate the presence of a context-ID.

How does this work? With the static model, we'd have an IANA registry for context IDs - how does one "use a bit" there?

**Comment by afrind** [comment]
Let me make a concrete example proposal:

First, forget you ever heard the word context :)

The varint at the beginning of a CONNECT UDP payload is as follows.

Two LSBs: ECN bits
Next LSB: Timestamp Present
All other bits: To be defined by other extensions

varint = 0 still means no extensions, just payload.

The IANA registry covers the standard usage of the other bits of the varint.  Does IANA allow you to do this?  In the worst case, every new bit registered doubles the number of entries in the registry.

This covers the two most common extension examples given in a very simple way.  It is more performant in the case of reordering of datagrams and registration capsules at the endpoint -- the datagram is always self-describing and can be processed immediately.  It requires no state or lookups.  It's also fewer bytes on the wire, but I don't think that's a convincing argument.

It doesn't require all extensions to be known at specification time either.  New extensions use new bits, and endpoints that don't support those extensions will drop the datagrams.  SETTINGS or Capsules or HTTP headers can be used to negotiate capabilities if that's desired.

**Comment by DavidSchinazi** [comment]
It sounds like you're proposing a flag field instead of an integer. That limits us to 62 extensions instead of 2^62. I don't think flags are the way to go, since not all extensions will be composable.

**Comment by afrind** [comment]
> That limits us to 62 extensions instead of 2^62

As Victor mentioned, you can always define the last flag to mean "more flags".  And I doubt we'll ever get to 62 extensions to CONNECT-UDP.

> not all extensions will be composable

I'm sympathetic to this argument on ideological grounds -- I don't like it to be possible to express a nonsensical combination of options. Do you have examples of extensions that are not composable?  Is it worth adding the complexity for the simplest and most common extensions to support these cases?

Can you list the advantages of dynamic context registration?

**Comment by bemasc** [comment]
There's a forecasting element here.  Here are some forecasts for extensions to CONNECT-UDP:

Metadata:

* ECN
* TIMESTAMP
* DSCP
* TTL

New contents:

* ICMP errors
* Datagram PING

Compressed representations:

* QUIC
* SRTP
* etc.

Header compression is highly stateful and dynamic, so it'll need the full dynamic context system.  Bitfield and dynamic contexts can be combined, but once you have dynamic contexts it's not clear to me what value the bitfield approach is adding.

Regarding incompatibility: PING cannot meaningfully be combined with ECN, nor with (say) a QUIC-specific header compression scheme.

**Comment by DavidSchinazi** [comment]
> As Victor mentioned, you can always define the last flag to mean "more flags". And I doubt we'll ever get to 62 extensions to CONNECT-UDP.

Small codepoint spaces make experimenting with draft extensions incredibly difficult, as we've seen with other protocols.

> Do you have examples of extensions that are not composable?

You can't compose ECN with the ping (PMTUD) extension.

> Is it worth adding the complexity for the simplest and most common extensions to support these cases?

What "complexity" is being added here? Capsules are not complex.

Also, we can't predict which extensions will be the most common.

> Can you list the advantages of dynamic context registration?

* It's more flexible: you can support all known types of extensions
* Base spec complexity is very minimal (see how short #70 is)
* Less procedural overhead: no added IANA registry
* No accidental composability of non-composable extensions
* Since this is very likely what we'll use for CONNECT-IP, this allows reusing code.

**Comment by achernya** [comment]
I'm not a fan of the flag register approach, and much prefer the varint with its 2^62 capabilities. I think that any "static allocation" that is used can be represented as early messages (as @DavidSchinazi proposed above) or could be side-band information in the headers attached to the request. In other words, I feel like from a CONNECT-UDP perspective, the "fully dynamic" model is actually preferable.

**Comment by afrind** [comment]
Thanks for the list of possible extensions and advantages -- that's really what I was trying to get when I opened the issue :) 

Looking at Ben's list, here's a non-flag based design that costs 1 byte for extensions:

1. The varint is one of [UDP Payload, UDP Payload with Metadata, PING, ICMP Error, Compressed UDP payload, future extension types...]
2. The extension types include the additional data they need -- maybe Metadata has a flags byte and Compressed UDP payload has a compression context ID.

I recognize the dynamic context registration mechanism solves this problem generically, and does so with minimal encoding on the wire.  The cost is that all extended datagrams must use the stateful context mechanism -- even those with no state (like PING) or state that's no larger than a context ID (ECN).  Even some extensions that have larger state might prefer to serialize it on the wire.  The QPACK dynamic table may be a good analogy: some clients choose to encode literal headers on the wire rather than mess with the state: even though it's demonstrably less wire-efficient, it's just simpler.

**Comment by DavidSchinazi** [comment]
Can you explain what you mean by "simpler"? To me the dynamic context registration system feels a lot simpler than this latest proposal, both simpler to implement and simpler to write the spec.

**Comment by afrind** [comment]
I think your view of what is simple is colored by having been invested in the stateful context approach for a long time and already having an implementation of it.  Instead take the view of someone new to the spec, with no code yet, who wants to write an extension.

Approach 1:

Define new datagram type
Send datagrams with new type
Parse datagrams with new type
Profit
Bonus: reordering is a no-op.

Approach 2:

Define new capsule type
Send capsule binding a context ID to the type
Send datagrams with context ID
Parse datagrams with context ID
Profit
Penalty: Datagram and Capsule re-ordering can cause buffering or drops at the receiver.
Penalty: The context has to be re-registered for every request
Security Consideration: Limiting the size of the context state

To me, approach 1 is simpler to implement and simpler to specify.  It doesn't preclude stateful extensions, it just requires them to send one extra byte.

**Comment by achernya** [comment]
> Penalty: Datagram and Capsule re-ordering can cause buffering or drops at the receiver.

That only exists if you opportunistically send the datagrams before waiting for the capsule registration acknowledgement, and also the receiver does not buffer the datagram in early connection startup.

> Penalty: The context has to be re-registered for every request

That also only exists if you do not define profiles with side-band information, which produces the Approach 1 flow you were desiring. This isn't a property of static vs dynamic, it's a property of a-priori knowledge. The only difference with approach 1 is you're requiring everyone to have a-priori knowledge. You can do that with a dynamic registration system too.

**Comment by DavidSchinazi** [comment]
> Penalty: Datagram and Capsule re-ordering can cause buffering or drops at the receiver.

That's not right. Both approaches need to handle the scenario where a DATAGRAM frame is reordered ahead of the STREAM frame that contains HEADERS. Any implementation of CONNECT-UDP needs to handle this scenario asynchronously, and registering on receiving headers vs registering on receiving capsule have the same complexity.

> Penalty: The context has to be re-registered for every request

Sending ~3 bytes is not a penalty worth worrying about.

> Security Consideration: Limiting the size of the context state

That's trivial for extensions that only need one type - you reset the stream if you receive a second capsule.

> To me, approach 1 is simpler to implement

Might I suggest implementing CONNECT-UDP? Your assumptions aren't quite right here.

> and simpler to specify.

I doubt it, if you'd like to write a PR for that approach I'm pretty sure it'll be longer than #70.

> It doesn't preclude stateful extensions, it just requires them to send one extra byte.

That type approach adds a layer of indirection which doesn't provide a lot of value. Abstractions aren't free.

**Comment by afrind** [comment]
> That also only exists if you do not define profiles with side-band information

I see, so perhaps I can define a SETTING that pre-allocates some context IDs to have certain meanings (does SETTINGS count as side-band)?

> The only difference with approach 1 is you're requiring everyone to have a-priori knowledge. You can do that with a dynamic registration system too

I didn't mean to imply that extensions wouldn't be negotiated in approach 1.  Perhaps the point is that if you use capsules for negotiation of extensions, and you do this per-request, then 1 and 2 look more similar.  There's still the issue of having to keep state and manage it when not all extensions require this.

**Comment by afrind** [comment]
> That's not right. Both approaches...

Agreed.  The machinery to buffer on reordering is the same.

> Sending ~3 bytes is not a penalty worth worrying about.

I never worry about the bytes.  The penalty is that you have to do it to make it work.

> That's trivial for extensions that only need one type - you reset the stream if you receive a second capsule.

It's even more trivial if it is impossible.  I put this under the same category as "non-composable extensions".  

> Might I suggest implementing CONNECT-UDP? Your assumptions aren't quite right here.

We have an implementation of CONNECT-UDP: https://github.com/facebook/proxygen/blob/main/proxygen/lib/http/session/HQSession.cpp#L3740

We always use context-ID 0, both because the machinery for contexts has been in a high state of flux, and because we've been hoping that their use is sequestered only to extensions that really require them.

> I doubt it, if you'd like to write a PR for that approach I'm pretty sure it'll be longer than #70

Here it is based on #70.  It's the same length.  The text is a few lines shorter and there's an IANA table.

https://github.com/afrind/draft-ietf-masque-connect-udp/pull/1

> Abstractions aren't free.

100%.  I think the context abstraction is the one with conceptual cost, hence I'm trying to isolate it only to use cases that cannot be accomplished any other way (compression).  "Define a new code point for your extension" seems to be a pretty common extension mechanism.

Maybe @martinthomson agrees?

**Comment by bemasc** [comment]
In my view, this proposal is likely "simpler" for endpoints that just support a handful of static, Mandatory-To-Implement extensions.  However, it is more complicated for a minimal implementation (because it introduces MTI extensions) and more complicated for a maximal implementation (which must implement both the bitfield-style and the dynamic-registration patterns).

> I see, so perhaps I can define a SETTING that pre-allocates some context IDs to have certain meanings

SETTINGS is hop-by-hop, so it would be a Header.  This is a reasonable pattern for "up-front allocation", but anything that can be done this way could also be done via Capsule.  Given the need for Capsule-based registration for dynamic extensions, adding a second registration mechanism seems like additive complexity.  This is why I think static allocation would only make sense for MTI extensions.  However, I don't see any of the proposed extensions as sufficiently valuable to warrant MTI status.

**Comment by kazuho** [comment]
Can we just use uint64_t for the IDs like QUIC v1, so that they would never collide?

I'm not following the discussion in the design group and I could well be missing something, but to me it seems that the necessity for negotiations stems from the desire to _always_ use a very compact representation for the IDs being used.

But we did not choose such a design in QUIC v1 which is our underlying protocol. In QUIC v1, we decided that we can allocate short frame IDs (below 64) for types that we think are going to be used frequently, while for less-frequently used frame IDs allocating numbers that require multi-byte encoding.

**Comment by martinthomson** [comment]
Varint encoding exists to support an asymmetric frequency distribution.  That might be the result of natural biases (core QUIC frames will be more common than most extension QUIC frames) or the result of the usage (low-numbered stream IDs are more common than high-numbered).  Whether varint is the right choice here depends largely on what is being identified.

And I think that Alan is suggesting something that might be a little less extensible or generic than what is being proposed otherwise.  That's reasonable.  This is UDP, for which the space of possibilities is pretty narrow.  We have a fair idea that some people will want ECN, some might want a subset of ICMP features, some might want flow labels, and some might have unanticipated needs.  Carving out space for "just UDP", "UDP with ECN", and "UDP with timestamps" might not be a bad use of a few bits, rather than using a generic system.

The potential for unanticipated needs suggests that some form of extension capability is worthwhile, but I think where we are disagreeing is the extent to which that capability needs to be central to the design.

If we (again) look at QUIC, the extension model for framing is pre-arrangement.  We don't have zero-latency setup for extensibility, even though some extensions can carry their extension across using 0-RTT.  That's simple, and we have reserved capacity in the frame types that allows endpoints to use those extensions seamlessly once they confirm that support is present.  But there the mapping is static: a given identifier means the same in every context, the negotiation only turns it on and off.

Dynamic allocation sounds dandy, but I think you are going to want to need it before going there.  For an intermediary that might ultimately want to forward at line rates, non-static mapping is more costly.  And it more costly at a conceptual level: you require access to state in order to make sense of anything.

A dynamic allocation policy is good if there is a need to tightly manage the number of bytes you are allocating.  Perhaps the number of identifiers is scarce (see RTP for an example) or maybe you are looking to make the most out of an MTU (connect-IP might benefit here).  Ben is right that if you don't need any of the extensibility, then it is easier to ignore it, but that depends on carving out some portion of the space for non-dynamic use (0 == datagram is very much static).  As soon as you decide that you need ECN, if ECN is dynamically negotiated, it's more complicated to implement than a purely static mapping.

For UDP forwarding, the number of use cases is limited.  I'd be relatively comfortable with Alan's idea.  I'd go further and ditch the varints.  Just have 8 flags, with two of those reserved for ECN.  We don't need a framework: other flags can be dynamically allocated; others might be statically allocated (the top two bits might be reserved for "8 more bits, 24 more bits, and 56 more bits" if you felt like it).  We don't necessarily have to decide now.  All that needs is that you require endpoints to discard datagrams with non-zero values in places they don't expect.

The story with IP does seem to be different as it seems like compression is more likely.

**Comment by bemasc** [comment]
I think QUIC header compression is likely to be an early, popular extension for CONNECT-UDP.  This is a fully dynamic extension: each context carries metadata that is not known until after the packets are flowing.

I predict that most CONNECT-UDP implementations will fall into one of two categories: "minimal" (no extensions, just plain UDP) and "kitchen sink" (tries to implement all defined extensions).  General-purpose libraries will have to cater to a wide variety of customers, so they'll implement everything.  Minimal implementations will be written in cases where a library can't be used (e.g. embedded systems, obscure programming languages) and "it works" is good enough.

Adding a header bitfield system doesn't help minimal implementers who don't care about ECN or timestamps or whatever, but it does make implementation more complex for the "kitchen sink" implementer, who already has a full implementation of dynamic registration for QUIC compression.

**Comment by tfpauly** [comment]
I've suggested to alternate options in #72. These both avoid all or some of the dynamic registration behavior, and also don't rely on flags fields. Thoughts are welcome!
